language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

script: mvn install
matrix:
  include:
    - jdk: openjdk7
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-overlay-example
    - jdk: oraclejdk7
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-rails-*
    - jdk: oraclejdk8
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-example
    - jdk: oraclejdk8
      script: cd restygwt; mvn verify -Prun-its -Dmaven.test.skip -Dinvoker.test=restygwt-jersey-*,restygwt-cxf-jaxson-*

